# Generated by Django 3.2.9 on 2022-10-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_carousel_customer_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='id',
        ),
        migrations.AddField(
            model_name='carousel',
            name='carousel_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
