# Generated by Django 3.2.9 on 2022-10-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.AddField(
            model_name='banner',
            name='image_url',
            field=models.CharField(blank=True, max_length=2083),
        ),
    ]
