# Generated by Django 3.2.9 on 2022-10-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20221005_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image_url',
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
