# Generated by Django 3.2.9 on 2022-10-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20221005_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.CharField(blank=True, max_length=30000),
        ),
    ]
