# Generated by Django 3.2.9 on 2022-10-04 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='category2',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
