# Generated by Django 3.2.9 on 2022-10-04 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_category2_banner_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
